# Generated by Django 4.1.7 on 2023-06-28 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Odor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raindrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='items')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=25990)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec10', models.IntegerField()),
                ('sec10per', models.IntegerField()),
                ('min', models.IntegerField()),
                ('minper', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('hourper', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dayper', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthper', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('geolocation', models.CharField(blank=True, max_length=250)),
                ('flame', models.ManyToManyField(blank=True, to='main.flame')),
                ('humidity', models.ManyToManyField(blank=True, to='main.humidity')),
                ('light', models.ManyToManyField(blank=True, to='main.light')),
                ('moisture', models.ManyToManyField(blank=True, to='main.moisture')),
                ('odor', models.ManyToManyField(blank=True, to='main.odor')),
                ('raindrop', models.ManyToManyField(blank=True, to='main.raindrop')),
                ('temperature', models.ManyToManyField(blank=True, to='main.temperature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='items')),
                ('fullname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=41)),
                ('experience', models.IntegerField(default=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='main.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialists'),
        ),
    ]
