# Generated by Django 4.1.7 on 2023-07-04 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='age',
            field=models.IntegerField(blank=True, default=41),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='city',
            field=models.CharField(blank=True, default='Astana', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='experience',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='photo',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
