# Generated by Django 4.1.7 on 2023-07-04 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_hour_flame_year_rename_hourper_flame_yearper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flame',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flame',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humidity',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humidity',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moisture',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moisture',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odor',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odor',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raindrop',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raindrop',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='weekper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flame',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flame',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='light',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odor',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odor',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raindrop',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='dayper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='minper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='monthper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='yearper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
