# Generated by Django 4.1.7 on 2023-07-05 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_flame_week_flame_weekper_humidity_week_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flame',
            new_name='Pressure',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='flame',
            new_name='pressure',
        ),
    ]
