# Generated by Django 4.1.7 on 2023-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
