# Generated by Django 4.1.7 on 2023-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_specialists_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='geolocation',
            new_name='geolocation1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='geolocation2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
