# Generated by Django 4.1.7 on 2023-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shapes_userprofile_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapes',
            name='shape',
            field=models.TextField(),
        ),
    ]
